services:
  wordpress:
    build: .
    ports:
      - "8000:8000"
    user: "1000:1000"
    volumes:
      - ../wp-content:/var/local/wordpress/wp-content
    environment:
      # OTel auto instrumentation config
      # https://opentelemetry.io/docs/instrumentation/php/automatic/#installation
      - OTEL_PHP_AUTOLOAD_ENABLED=true
      - OTEL_SERVICE_NAME=ca.k3p.rhildred.INFO8985-observable-monolith
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - WP_MEMORY_LIMIT=512M
    depends_on:
      - otel-collector
  custom-contact-form:
    build: ../contact-form
    ports:
      - "8001:8001"
    environment:
      - OTEL_SERVICE_NAME=contact-form
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - SENDGRID_API_KEY=
      - SENDGRID_FROM_EMAIL= prabhdeepsinghgill1@gmail.custom
      - SENDGRID_TO_EMAIL=prabhdeepsinghgill1can@gmail.com

    depends_on:
      - otel-collector

networks:
  observability: